[package]
name = "geos"
version = "0.1.0"
authors = ["Graham Keenan <grahamkeenan@hotmail.co.uk>"]
edition = "2018"

[package.metadata.bootimage]
default-target = "x86_64-geos.json"

[dependencies]
bootloader = "0.3.4"